src/accounts/urls.py
from django.urls import include, path

from .views import accounts, profile
from posts import views as posts

urlpatterns = [
    path('logout/', accounts.logout_view, name='logout'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', accounts.UserSignUpView.as_view(), name='user_signup'),
    path('accounts/signup/success/', accounts.signup_success, name='success'),
    path('profile/', include(([
        path('<int:pk>/', posts.wall, name='wall'),
        path('<int:pk>/posts/', posts.timeline, name='timeline'),
        path('load-posts/', posts.load_posts, name='load-posts'),
    ], 'accounts'), namespace='profile')),
    path('community/', include(([
        path('', profile.people_list, name='people'),
    ], 'accounts'), namespace='community')),
    path('contacts/', include(([
        path('<int:pk>/', profile.contacts_list, name='pro_contacts'),
        path('<int:pk>/send-request', profile.send_contact_request, name='send_request'),
        path('<int:pk>/contact-requests', profile.contact_requests, name='contact_requests'),
        path('<int:pk>/contact-response', profile.contact_response, name='contact_response'),
    ], 'accounts'), namespace='contacts')),
]

src/characters/urls.py
from django.urls import include, path

from . import views

urlpatterns = [
    path('characters/', include(([
        path('<int:pk>/', views.creator_characters, name='my-characters'),
        path('create/', views.create_character, name="create"),
    ], 'characters'), namespace='characters')),
]

src/files/urls.py
from django.urls import include, path

from . import views

urlpatterns = [
    path('files/', include(([
        path('', views.files_home_view, name="files_home"),
        path('download/', views.download_view, name="download_file"),
    ], 'files'), namespace='files')),
]

src/openlit/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('pages.urls')),
    path('', include('characters.urls')),
    path('', include('stories.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/stories/urls.py
from django.urls import include, path

from . import views

urlpatterns = [
    path('', include(([
        path('stories/creator/<int:pk>/', views.author_stories, name='my-stories'),
        path('stories/create/', views.create_story, name="create"),
        path('stories/<int:pk>/view', views.story_details, name='view'),
        path('stories/<int:pk>/characters', views.story_characters, name='story-characters'),
        path('stories/<int:pk>/author-characters', views.author_characters, name='author-characters'),
        path('stories/<int:pk>/character-assignment/', views.assign_character, name='assign-character'),
        path('stories/<int:pk>/acts/', views.act_list, name='act-list'),
        path('stories/<int:pk>/act-create/', views.act_create, name='act-create'),
        path('acts/<int:pk>/', views.act_details, name='act-view'),
        path('act/<int:pk>/scene-create/', views.scene_create, name='scene-create'),
        path('scenes/<int:pk>/', views.scene_details, name='scene-view'),
    ], 'stories'), namespace='stories')),
]

src/templates/partials/footer.html
<div class="footer deep-lilac">
    {% comment %} footer links credits, terms of service {% endcomment %}
    <strong>OPENLIT</strong>&nbsp; &copy;
    <script>
        document.write(new Date().getFullYear())
    </script>
</div>

src/templates/partials/navbar.html
<nav class="navbar fixed-top navbar-expand-lg navbar-dark deep-lilac opac">
  <a class="navbar-brand" href="#">OpenLit</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item {% if request.resolver_match.url_name == 'home' %}active{% endif %}">
        <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      
      {% if request.user.is_authenticated %}
        <li class="nav-item {% if request.resolver_match.url_name == 'wall' %}active{% endif %}">
          <a class="nav-link" href="{% url 'profile:wall' request.user.profile.id %}">Profile</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
        </li>
      {% else %}
        <li class="nav-item {% if request.resolver_match.url_name == 'user_signup' %}active{% endif %}">
          <a class="nav-link" href="{% url 'user_signup' %}">Signup</a>
        </li>
        <li class="nav-item {% if request.resolver_match.url_name == 'login' %}active{% endif %}">
          <a class="nav-link" href="{% url 'login' %}">Login</a>
        </li>
      {% endif %}
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2 rounded-pill deep-lilac-border" type="text" placeholder="Search">
      <button class="btn old-glory-blue-bg my-2 my-sm-0 text-white" type="submit">Search</button>
    </form>
  </div>
</nav>

src/templates/partials/side-nav.html
<!-- Sidebar Holder -->
<nav id="sidebar">
    <div class="sidebar-header">
        <h3>OpenLit</h3>
    </div>

    <ul class="list-unstyled components">
        <p>{{ request.user.name }}</p>
        <li class="active">
            <a href="#">Home</a>
        </li>
        <li>
            <a href="{% url 'characters:my-characters' request.user.profile.id %}">Characters</a>
        </li>
        <li>
            <a href="{% url 'stories:my-stories' request.user.profile.id %}">Stories</a>
        </li>
    </ul>
</nav>

src/templates/partials/sidebar.html
<!--
    a list for the side bar and the list should display the category name
-->

<div class="card mb-3" style="width: 100%;">
    <div class="card-header">
        Categories
    </div>
    <ul class="list-group list-group-flush">
        {% for category in qs %}
                <li class="list-group-item"><a href="#">{{ category.name }}</a></li>
        {% endfor %}
    </ul>
</div>

src/templates/partials/topbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">

        <button type="button" id="sidebarCollapse" class="navbar-btn">
            <span></span>
            <span></span>
            <span></span>
        </button>
        <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <i class="fas fa-align-justify"></i>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="nav navbar-nav ml-auto">
                {% if section == 'Wall' %}
                    <li class="nav-item active">
                        <a class="nav-link" href="#">Timeline</a>
                    </li>
                {% elif section == 'Characters' %}
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'characters:create' %}">Create</a>
                    </li>
                    {% elif section == 'Story' %}
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'stories:create' %}">Create</a>
                        </li>
                    {% elif section == 'StoryDetails' %}
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'stories:view' story.id %}">{{ story.title }}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'stories:story-characters' story.id %}">Characters</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'stories:act-list' story.id %}">Acts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Images</a>
                        </li>
                    {% elif section == 'Act' %}
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'stories:act-view' act.id %}">{{ act.title }}</a>
                        </li>
                    {% else %}
                    
                    <li class="nav-item">
                        <a class="nav-link" href="#">Page</a>
                    </li>
                {% endif %}
                
            </ul>
        </div>
    </div>
</nav>