src/accounts/urls.py
from django.urls import include, path

from .views import accounts, profile
from posts import views as posts

urlpatterns = [
    path('logout/', accounts.logout_view, name='logout'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', accounts.UserSignUpView.as_view(), name='user_signup'),
    path('accounts/signup/success/', accounts.signup_success, name='success'),
    path('profile/', include(([
        path('<int:pk>/', posts.wall, name='wall'),
        path('<int:pk>/posts/', posts.timeline, name='timeline'),
        path('load-posts/', posts.load_posts, name='load-posts'),
    ], 'accounts'), namespace='profile')),
    path('community/', include(([
        path('', profile.people_list, name='people'),
    ], 'accounts'), namespace='community')),
    path('contacts/', include(([
        path('<int:pk>/', profile.contacts_list, name='pro_contacts'),
        path('<int:pk>/send-request', profile.send_contact_request, name='send_request'),
        path('<int:pk>/contact-requests', profile.contact_requests, name='contact_requests'),
        path('<int:pk>/contact-response', profile.contact_response, name='contact_response'),
    ], 'accounts'), namespace='contacts')),
]

src/files/urls.py
from django.urls import include, path

from . import views

urlpatterns = [
    path('files/', include(([
        path('', views.files_home_view, name="files_home"),
        path('download/', views.download_view, name="download_file"),
    ], 'files'), namespace='files')),
]

src/openlit/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('pages.urls')),
    path('', include('characters.urls')),
    path('', include('stories.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/accounts/models.py
import uuid
from django.conf import settings
from django.db import models
from django.urls import reverse_lazy
from django.utils.translation import ugettext_lazy as _


class UserProfileManager(models.Manager):
    use_for_related_fields = True

# Create your models here. 
class UserProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, related_name="profile", on_delete=models.CASCADE)
    contacts = models.ManyToManyField('self', related_name='contacts', blank=True)

    objects = UserProfileManager()

    def __str__(self):
        return self.user.username

class ContactRequest(models.Model):
    # user requesting
    sender = models.ForeignKey(UserProfile, related_name='requests_sent', on_delete=models.CASCADE)
    
    # user requested
    receiver = models.ForeignKey(UserProfile, related_name='requests_received' , on_delete=models.CASCADE)
    
    # status
    status = models.BooleanField(default=False)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Follow(models.Model):
    followed = models.ForeignKey(UserProfile, related_name='following', on_delete=models.CASCADE)
    follower = models.ForeignKey(UserProfile, related_name='followed_by', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

src/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import Group
from django.db import transaction
from django.forms.utils import ValidationError

from accounts.models import UserProfile
from files.models import Folder
from photos.models import Album, Photo
from users.models import User

class UserSignUpForm(UserCreationForm):
    username = forms.CharField(min_length=1, max_length=30, widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.CharField(min_length=1, max_length=60, widget=forms.EmailInput(attrs={'class': 'form-control'}))
    name = forms.CharField(min_length=1, max_length=60, widget=forms.TextInput(attrs={'class': 'form-control'}))
    photo = forms.ImageField(widget=forms.FileInput(attrs={'class': 'form-control-file'}))
    password1 = forms.CharField(min_length=1, max_length=60, widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(min_length=1, max_length=60, widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    class Meta(UserCreationForm):
        model = User
        fields = ('username', 'name', 'email', 'photo',)

    @transaction.atomic
    def save(self):
        user = super().save()
        profile = UserProfile.objects.create(user=user)
        album = Album.objects.create(name=user.username, owner=profile)
        Photo.objects.create(file=self.cleaned_data.get('photo'), album=album, default=True)
        profile.albums.add(album)
        Folder.objects.create(name='Shared', creator=profile)
        Folder.objects.create(name=user.username, creator=profile)
        return user

src/accounts/views/accounts.py
from django.contrib.auth import logout, login
from django.shortcuts import redirect, render
from django.views.generic.edit import CreateView

from accounts.forms import UserSignUpForm
from accounts.models import UserProfile
from users.models import User

# Create your views here.

class UserSignUpView(CreateView):
    model = User
    form_class = UserSignUpForm
    template_name = 'auth/signup_form.html'

    def get_context_data(self, **kwargs):
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('profile:wall', user.profile.id)


def signup_success(request, template_name='auth/success.html'):
    return render(request, template_name)

def logout_view(request):
    logout(request)
    return redirect('home')

src/accounts/views/profile.py
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render

from users.decorators import group_required
from users.models import User
from accounts.models import UserProfile, ContactRequest

@login_required
def user_profile(request, pk, template_name='accounts/profile/index.html'):
    profile = get_object_or_404(UserProfile, pk=pk, user=request.user)
    data = {}
    data['profile'] = profile
    return render(request, template_name, data)

@login_required
def people_list(request, template_name='accounts/profile/people.html'):
    # get list of all users
    people = UserProfile.objects.exclude(user=request.user)
    # set up data context
    data = {}
    data['people'] = people
    
    return render(request, template_name, data)

@login_required
def send_contact_request(request, pk):
    # get current user (befriender)
    profile = UserProfile.objects.get(pk=pk)

    # get user that is being befriended
    if request.method == 'POST':
        contact = request.POST['contact']

        contact_profile = UserProfile.objects.get(pk=contact)

        # create a friendship
        contact_request = ContactRequest.objects.create(sender=profile, receiver=contact_profile)
    # return response
    return HttpResponse('')

@login_required
def contact_requests(request, pk, template_name='contacts/contact_requests.html'):
    # get list of user contact requests
    user = get_object_or_404(UserProfile, pk=pk, user=request.user)
    requests = ContactRequest.objects.filter(receiver=user, status=False)

    data = {}

    data['requests'] = requests

    return render(request, template_name, data)

@login_required
@transaction.atomic
def contact_response(request, pk):
    current_user = UserProfile.objects.get(pk=pk, user=request.user)
    if request.method == 'POST':
        status = int(request.POST['status'])
        contact = request.POST['contact']
        sender = UserProfile.objects.get(pk=contact)

        # get request
        contact_request = ContactRequest.objects.get(sender=sender, receiver=current_user)

        # update request
        if (status == 1):
            contact_request.status = status
            contact_request.save()
            current_user.contacts.add(sender)
            sender.contacts.add(current_user)
     # return response
    return HttpResponse('')


@login_required
def contacts_list(request, pk, template_name='contacts/contacts_list.html'):
    profile = UserProfile.objects.get(pk=pk)
    data = {}
    data['pro'] = profile
    return render(request, template_name, data)

src/accounts/templates/accounts/profile/contact_requests.html
{% extends 'profile.html' %}

{% block content %}
    <div class="my-3">
        <a class="btn btn-outline-primary" href="{% url 'contacts:pro_contacts' request.user.profile.id %}" role="button">My Contacts</a>
        <a class="btn btn-outline-primary" href="#" role="button">People</a>
    </div>
    {% for contact in requests %}
        <div class="card">
            <div class="card-body">
                <p>{{ contact.sender.user.name }}</p>
                <form id="res-form-{{contact.id}}">
                    {% csrf_token %}
                    <div class="form-group">
                        <select class="form-control" id="status" name="status">
                            <option value="1">Accept</option>
                            <option value="0">Deny</option>
                        </select>
                    </div>
                    <input type="hidden" id="res-{{contact.sender.id}}" value="{{ contact.sender.id }}" />
                    <button type="submit" onclick="addContact('res-form-{{contact.id}}', {{contact.sender.id}})"  class="btn btn-primary btn-round">Respond</button>
                </form>
            </div>
        </div>
        {% comment %} 
            {% for group in person.groups.all %}{{ group.name }}{% endfor %} 
        {% endcomment %}
    {% endfor %}
{% endblock content %}

{% block javascript %}
    <script type="text/javascript">
        addContact = function(form_id, user_id) {
            form_selector = '#' + form_id;
            user_selector = '#res-' + user_id;
            url = "{% url 'contacts:contact_response' request.user.profile.id %}";

            $(document).on('submit', form_selector, function(e) {
                e.preventDefault();
                
                $.ajax({
                    type: 'POST',
                    url: url,
                    data: {
                        status: $('#status').val(),
                        contact: $(user_selector).val(),
                        csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
                    }, 
                    success: function() {
                        alert('Contact added!');
                    }
                });
            });
        };
    </script>
{% endblock javascript %}

src/accounts/templates/accounts/profile/contacts_list.html
{% extends 'profile.html' %}

{% block content %}
    <div class="my-3">
        <a class="btn btn-outline-primary" href="#" role="button">My Contacts</a>
        <a class="btn btn-outline-primary" href="{% url 'contacts:contact_requests' request.user.profile.id %}" role="button">Requests</a>
    </div>
    {% for person in pro.contacts.all %}
        <div class="card">
            <div class="card-body">
                <p>{{ person.name }}</p>
            </div>
        </div>
        {% comment %} 
            {% for group in person.groups.all %}{{ group.name }}{% endfor %} 
        {% endcomment %}
    {% endfor %}
{% endblock content %}

src/accounts/templates/accounts/profile/followers.html
{% extends 'profile.html' %}

{% block content %}
    <h1 class="py-3">Followers</h1>
    {% for person in followers %}
        <div class="card">
            <div class="card-body">
                <p>{{ person.follower.user.name }}</p>
            </div>
        </div>
        {% comment %} 
            {% for group in person.groups.all %}{{ group.name }}{% endfor %} 
        {% endcomment %}
    {% endfor %}
{% endblock content %}

src/accounts/templates/accounts/profile/following.html
{% extends 'profile.html' %}

{% block content %}
    <h1 class="py-3">Following</h1>
    {% for person in following %}
        <div class="card">
            <div class="card-body">
                <p>{{ person.followed.user.name }}</p>
            </div>
        </div>
        {% comment %} 
            {% for group in person.groups.all %}{{ group.name }}{% endfor %} 
        {% endcomment %}
    {% endfor %}
{% endblock content %}

src/accounts/templates/accounts/profile/index.html
{% extends 'profile.html' %}

{% block content %}
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a href="" data-target="#feed" data-toggle="tab" class="nav-link active">Feed</a>
        </li>
        <li class="nav-item">
            <a href="" data-target="#messages" data-toggle="tab" class="nav-link">Messages</a>
        </li>
    </ul>
                
    <div class="tab-content py-4">
        <div class="tab-pane" id="feed">
            <p>No content</p>
        </div>
        <div class="tab-pane" id="messages">
            <p>No content</p>
        </div>
    </div>
{% endblock content %}

src/accounts/templates/accounts/profile/people.html
{% extends 'profile.html' %}

{% block content %}
    <div class="my-3">
        <a class="btn btn-outline-primary" href="#" role="button">My Contacts</a>
        <a class="btn btn-outline-primary" href="{% url 'contacts:contact_requests' request.user.profile.id %}" role="button">Requests</a>
    </div>
    {% for person in people %}
        <div class="card">
            <div class="card-body">
                <h2>{{ person.user.name }}</h2>
                <div class="row">
                    <div class="col">
                        <form id="req-form-{{person.id}}">
                            {% csrf_token %}
                            <input type="hidden" id="req-{{person.id}}" value="{{ person.id }}" />
                            <button type="submit" onclick="contactRequest('req-form-{{person.id}}', {{person.id}})"  class="btn btn-outline-primary btn-block">Contact</button>
                        </form>
                    </div>
                    <div class="col">
                        <form id="f-form-{{person.id}}">
                            {% csrf_token %}
                            <input type="hidden" id="f-{{person.id}}" value="{{ person.id }}" />
                            <button type="submit" onclick="follow('f-form-{{person.id}}', {{person.id}})"  class="btn btn-outline-primary btn-block">Follow</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        {% comment %} 
            {% for group in person.groups.all %}{{ group.name }}{% endfor %} 
        {% endcomment %}
    {% endfor %}
{% endblock content %}

{% block javascript %}
    <script type="text/javascript">

        /*var socket = new WebSocket('ws://' + window.location.host + '/users/');

        socket.onopen = function open() {
            console.log('WebSockets connection created.');
        };

        if (socket.readyState == WebSocket.OPEN) {
            socket.onopen();
        }*/

        contactRequest = function(form_id, user_id) {
            form_selector = '#' + form_id;
            user_selector = '#req-' + user_id;
            url = "{% url 'contacts:send_request' request.user.profile.id %}";
            

            $(document).on('submit', form_selector, function(e) {
                e.preventDefault();
                
                $.ajax({
                    type: 'POST',
                    url: url,
                    data: {
                        contact: $(user_selector).val(),
                        csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
                    }, 
                    success: function(data) {
                        alert("Contact request sent!");
                    }
                });
            });
        };
        follow = function(form_id, user_id) {
            form_selector = '#' + form_id;
            user_selector = '#f-' + user_id;
            url = "{% url 'community:follow' request.user.profile.id %}";

            $(document).on('submit', form_selector, function(e) {
                e.preventDefault();
                
                $.ajax({
                    type: 'POST',
                    url: url,
                    data: {
                        follow: $(user_selector).val(),
                        csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
                    }, 
                    success: function() {
                        alert('Now following');
                    }
                });
            });
        };

    </script>
{% endblock javascript %}