src/files/urls.py
from django.urls import include, path

from . import views

urlpatterns = [
    path('files/', include(([
        path('', views.files_home_view, name="files_home"),
        path('download/', views.download_view, name="download_file"),
    ], 'files'), namespace='files')),
]

src/openlit/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('pages.urls')),
    path('', include('characters.urls')),
    path('', include('stories.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/stories/urls.py
from django.urls import include, path

from . import views

urlpatterns = [
    path('', include(([
        path('stories/creator/<int:pk>/', views.author_stories, name='my-stories'),
        path('stories/create/', views.create_story, name="create"),
        path('stories/<int:pk>/view', views.story_details, name='view'),
        path('stories/<int:pk>/characters', views.story_characters, name='story-characters'),
        path('stories/<int:pk>/author-characters', views.author_characters, name='author-characters'),
        path('stories/<int:pk>/character-assignment/', views.assign_character, name='assign-character'),
        path('stories/<int:pk>/acts/', views.act_list, name='act-list'),
        path('stories/<int:pk>/act-create/', views.act_create, name='act-create'),
        path('acts/<int:pk>/', views.act_details, name='act-view'),
        path('act/<int:pk>/scene-create/', views.scene_create, name='scene-create'),
        path('scenes/<int:pk>/', views.scene_details, name='scene-view'),
    ], 'stories'), namespace='stories')),
]

src/stories/models.py
from django.db import models

from accounts.models import UserProfile
from characters.models import Character
from photos.models import Album

# Create your models here.
class Story(models.Model):
    title = models.CharField(max_length=255)
    premise = models.CharField(max_length=300, null=True, blank=True)
    time = models.CharField(max_length=255, null=True, blank=True)
    place = models.CharField(max_length=255, null=True, blank=True)
    album = models.OneToOneField(Album, on_delete=models.CASCADE, null=True, blank=True)
    author = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='stories')
    characters = models.ManyToManyField(Character, through='StoryCharacter', blank=True)

    def __str__(self):
        return self.title

class StoryCharacter(models.Model):
    ROLE_CHOICE_TYPES = (
        ('Protagonist', 'Protagonist'),
        ('Deuteragonist', 'Deuteragonist'),
        ('Antagonist', 'Antagonist'),
        ('Love Interest', 'Love Interest'),
        ('Mentor', 'Mentor'),
        ('Narrator', 'Narrator'),
        ('Secondary', 'Secondary Character'),
        ('Tertiary', 'Tertiary Character'),
        ('Flat', 'Flat Character'),
    )

    character = models.ForeignKey(Character, on_delete=models.CASCADE, related_name='stories')
    story = models.ForeignKey(Story, on_delete=models.CASCADE)
    role = models.CharField(max_length=100, choices=ROLE_CHOICE_TYPES)

class Act(models.Model):
    act_number = models.PositiveIntegerField()
    title = models.CharField(max_length=255)
    about = models.TextField(null=True, blank=True)
    story = models.ForeignKey(Story, on_delete=models.CASCADE, related_name='acts')

    def __str__(self):
        return self.title

class Scene(models.Model):
    title = models.CharField(max_length=255)
    time = models.CharField(max_length=255, null=True, blank=True)
    place = models.CharField(max_length=255, null=True, blank=True)
    weather = models.CharField(max_length=255, null=True, blank=True)
    setup = models.TextField(null=True, blank=True)
    action = models.TextField(null=True, blank=True)
    position = models.PositiveIntegerField()
    act = models.ForeignKey(Act, on_delete=models.CASCADE, related_name='scenes')
    characters = models.ManyToManyField(Character, related_name='scenes', blank=True)

    def __str__(self):
        return self.title

class Dialogue(models.Model):
    scene = models.ForeignKey(Scene, on_delete=models.CASCADE, related_name='dialogues')
    character = models.ForeignKey(Character, on_delete=models.CASCADE, related_name='dialogues')
    content = models.TextField()

src/stories/forms.py
from django import forms
from django.db import transaction
from .models import Story, Act, Scene, Dialogue
from accounts.models import UserProfile

class StoryForm(forms.ModelForm):
    title = forms.CharField(max_length=255, widget=forms.TextInput(attrs={'class':'form-control rounded-pill'}))
    photo = forms.ImageField(widget=forms.FileInput(attrs={'class': 'form-control-file'}))
    #recipients = forms.ModelMultipleChoiceField(widget=forms.SelectMultiple(attrs={'class':'form-control'}))
    # published = forms.BooleanField(required=False, widget=forms.CheckboxInput(attrs={'class': 'form-check-input'}))
    
    class Meta:
        model = Story
        fields = ['title', 'photo']

class ActForm(forms.ModelForm):
    act_number = forms.IntegerField(widget=forms.NumberInput(attrs={'class':'form-control rounded-pill'}))
    title = forms.CharField(max_length=255, widget=forms.TextInput(attrs={'class':'form-control rounded-pill'}))

    class Meta:
        model = Act
        fields = ['act_number', 'title']

class SceneForm(forms.ModelForm):
    position = forms.IntegerField(widget=forms.NumberInput(attrs={'class':'form-control rounded-pill'}))
    title = forms.CharField(max_length=255, widget=forms.TextInput(attrs={'class':'form-control rounded-pill'}))

    class Meta:
        model = Scene
        fields = ['position', 'title']

class DialogueForm(forms.ModelForm):
    content = forms.CharField(widget=forms.Textarea(attrs={'class' : 'form-control', 'rows':'3'}))

    class Meta:
        model = Dialogue
        fields = ['content']

src/stories/views.py
import simplejson as json
from django.db import transaction
from django.db.models import Q
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404

from .forms import StoryForm, ActForm, SceneForm, DialogueForm
from .models import Story, StoryCharacter, Act, Scene, Dialogue
from accounts.models import UserProfile
from characters.models import Character
from photos.models import Album, Photo

def author_stories(request, pk, template_name='stories/index.html', data={}):
    author = UserProfile.objects.get(pk=pk, user=request.user)
    stories = Story.objects.filter(author=author)
    data['stories'] = stories
    data['section'] = 'Story'
    return render(request, template_name, data)

def create_story(request, template_name='stories/story_form.html', data={}):
    if request.method == 'POST':
        form = StoryForm(request.POST, request.FILES)
        if form.is_valid():
            c = form.save(commit=False)
            c.author = request.user.profile
            album = Album.objects.create(name=c.title, owner=request.user.profile)
            photo = Photo.objects.create(file=form.cleaned_data['photo'], default=True, album=album)
            c.album = album
            c.save()
            return redirect('stories:my-stories', request.user.profile.id)
    else:
        form = StoryForm()
    data['form'] = form
    data['section'] = 'Story'
    return render(request, template_name, data)

def story_details(request, pk, template_name='stories/story_details.html', data={}):
    story = Story.objects.get(pk=pk, author=request.user.profile)
    characters = StoryCharacter.objects.filter(story=story)
    data['story'] = story
    data['characters'] = characters
    data['section'] = 'StoryDetails'
    return render(request, template_name, data)

def story_characters(request, pk, template_name='stories/story_characters.html', data={}):
    story = Story.objects.get(pk=pk, author=request.user.profile)
    data['story'] = story
    data['section'] = 'StoryDetails'
    return render(request, template_name, data)

def author_characters(request, pk, template_name='stories/author_characters.html', data={}):
    story = Story.objects.get(pk=pk, author=request.user.profile)
    story_characters = StoryCharacter.objects.filter(story=story).values('character')
    characters = Character.objects.filter(creator=request.user.profile).exclude(pk__in=story_characters)

    data['characters'] = characters
    data['story'] = story
    data['section'] = 'StoryDetails'
    return render(request, template_name, data)

@transaction.atomic
def assign_character(request, pk):

    if request.method == 'POST':
        character_id = request.POST['character']
        role = request.POST['role']

        character = Character.objects.get(pk=character_id)
        story = Story.objects.get(pk=pk, author=request.user.profile)

        story_character = StoryCharacter.objects.create(character=character, story=story, role=role)

        message = "%s has been assigned to %s" %(character.name, story.title)
        data = {'message': message}
        return JsonResponse(data)
    # return response
    return HttpResponse('')

def act_list(request, pk, template_name='stories/act_list.html', data={}):
    story = Story.objects.get(pk=pk)
    acts = Act.objects.filter(story=story).order_by('-act_number')
    data['story'] = story
    data['acts'] = acts
    data['section'] = 'StoryDetails'
    return render(request, template_name, data)

def act_create(request, pk, template_name='stories/act_form.html', data={}):
    story = Story.objects.get(pk=pk)
    form = ActForm(request.POST or None)
    if form.is_valid():
        c = form.save(commit=False)
        c.story = story
        c.save()
        return redirect('stories:act-list', story.id)
    data['story'] = story
    data['form'] = form
    data['section'] = 'StoryDetails'
    return render(request, template_name, data)

def act_details(request, pk, template_name='stories/act_details.html', data={}):
    act = Act.objects.get(pk=pk)
    scenes = Scene.objects.filter(act=act).order_by('-position')
    data['act'] = act
    data['scenes'] = scenes
    data['section'] = 'Act'
    return render(request, template_name, data)

def scene_create(request, pk, template_name='stories/scene_form.html', data={}):
    act = Act.objects.get(pk=pk)
    form = SceneForm(request.POST or None)

    if form.is_valid():
        c = form.save(commit=False)
        c.act = act
        c.save()
        return redirect('stories:act-view', act.id)
    data['form'] = form
    data['act'] = act
    data['section'] = 'Act'
    return render(request, template_name, data)

def scene_details(request, pk, template_name='stories/scene_details.html', data={}):
    scene = Scene.objects.get(pk=pk)
    act = Act.objects.get(pk=scene.act.id)
    data['act'] = act
    data['scene'] = scene
    data['section'] = 'Act'
    return render(request, template_name, data)

src/stories/templates/stories/act_details.html
{% extends 'profile.html' %}

{% block content %}
<div class="container-fluid">

    <div class="row">
        <header class="col">
            <div class="jumbotron">
                <h1 class="display-4">{{ act.title }}</h1>
                <p class="lead">About text goes here.</p>
            </div>
        </header>
    </div>
    <div class="row mb-3">
        <div class="col">
            <a class="btn btn-primary" href="{% url 'stories:scene-create' act.id %}">Add Scene</a>
        </div>
    </div>
    <div class="card-columns">
        {% for scene in scenes %}
        <div class="card">
            <div class="card-body">
                <h4 class="card-title"><a href="{% url 'stories:scene-view' scene.id %}">{{ scene.title }}</a></h4>
            </div>
        </div>
        {% empty %}
            <p>You haven't created any scenes</p>
        {% endfor %}
        
    </div>
</div>
{% endblock content %}

src/stories/templates/stories/act_form.html
{% extends 'profile.html' %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col">
            <h1 class="py-3">Create Act</h1>
            <form class="pb-3" method="post" novalidate>
                {% csrf_token %}
                <div class="form-group">
                    {{ form.title.errors }}
                    <label for="{{ form.title.id_for_label }}">Title:</label>
                    {{ form.title }}
                </div>
                <div class="form-group">
                    {{ form.act_number.errors }}
                    <label for="{{ form.act_number.id_for_label }}">Act Number:</label>
                    {{ form.act_number }}
                </div>
                <button type="submit" class="btn btn-primary rounded-pill">Save</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

src/stories/templates/stories/act_list.html
{% extends 'profile.html' %}

{% block content %}
<div class="container-fluid">

    <div class="row mb-3">
        <div class="col">
            <a class="btn btn-primary" href="{% url 'stories:act-create' story.id %}">Add Act</a>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <table class="table table-striped table-responsive">
                <thead>
                    <tr>
                        <th>Act Number</th>
                        <th>Title</th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for act in acts %}
                            <tr>
                                <td scope="row">{{ act.act_number }}</td>
                                <td><a href="{% url 'stories:act-view' act.id %}">{{ act.title }}</a></td>
                            </tr>
                        {% endfor %}
                    </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock content %}

src/stories/templates/stories/author_characters.html
{% extends 'profile.html' %}

{% block content %}
{% include 'modals/hard-modal.html' %}
<div class="container-fluid">
    <div class="row">
        <div class="col">
            <h1 class="py-3">Choose Character</h1>
        </div>
    </div>

    <div class="card-columns">
        {% for character in characters %}
        <div class="card">
            {% for photo in character.album.photos.all %}
                {% if photo.default and photo.album.name == character.album.name  %}
                    <img src="{{ MEDIA_URL }}{{photo.file}}" class="card-img-top" 
                    style="object-fit: cover; object-position: 100% 0; height: 337px;" alt="...">
                {% endif %}
            {% endfor %}
            <div class="card-body">
                <h4 class="card-title">{{ character.name }}</h4>
                <form id="scform-{{ character.id }}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="character-{{ character.id }}" id="character-{{ character.id }}" value="{{ character.id }}">
                    <div class="form-group">
                      <label for="role">Role</label>
                      <select class="form-control" name="role-{{ character.id }}" id="role-{{ character.id }}">
                        <option>Select a role for your character</option>
                        <option value="Protagonist">Protagonist</option>
                        <option value="Deuteragonist">Deuteragonist</option>
                        <option value="Antagonist">Antagonist</option>
                        <option value="Love Interest">Love Interest</option>
                        <option value="Mentor">Mentor</option>
                        <option value="Narrator">Narrator</option>
                        <option value="Secondary">Secondary Character</option>
                        <option value="Tertiary">Tertiary Character</option>
                        <option value="Flat">Flat Character</option>
                      </select>
                    </div>
                    <button type="submit" class="btn btn-primary" onclick="assignCharacter('#scform-{{ character.id }}', '#character-{{ character.id }}', '#role-{{ character.id }}')">
                        Choose
                    </button>
                </form>
            </div>
        </div>
        {% empty %}
            <p>
                No characters available
            </p>
        {% endfor %}
    </div>
</div>

{% endblock content %}

{% block javascript %}
<script type="text/javascript">
    assignCharacter = function(form, character_id, role_id) {

        url = "{% url 'stories:assign-character' story.id %}";

        $(document).on('submit', form, function(e) {
            e.preventDefault();
            
            $.ajax({
                type: 'POST',
                url: url,
                data: {
                    csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
                    character: $(character_id).val(),
                    role: $(role_id).val(),
                }, 
                success: function(data) {
                    $('#message').html(data.message);
                    $('#hardModal').modal({
                        backdrop: 'static',
                        keyboard: false
                    });
                }
            });
        });
    };
</script>
{% endblock javascript %}

src/stories/templates/stories/dialogue_form.html
{% extends 'profile.html' %}

{% block content %}
{% endblock content %}

src/stories/templates/stories/index.html
{% extends 'profile.html' %}

{% block content %}

<div class="container-fluid">

    <div class="row">
        <header class="col">
            <h1>Stories</h1>
        </header>
    </div>

    <div class="card-columns">
        {% for story in stories %}
        <div class="card">
            {% for photo in story.album.photos.all %}
                {% if photo.default and photo.album.name == story.album.name  %}
                    <img src="{{ MEDIA_URL }}{{photo.file}}" class="card-img-top" 
                    style="object-fit: cover; object-position: 100% 0; height: 337px;" alt="...">
                {% endif %}
            {% endfor %}
            <div class="card-body">
                <h4 class="card-title"><a href="{% url 'stories:view' story.id %}">{{ story.title }}</a></h4>
            </div>
        </div>
        {% empty %}
            <p>You haven't created any stories</p>
        {% endfor %}
        
    </div>
</div>

{% endblock content %}

src/stories/templates/stories/scene_details.html
{% extends 'profile.html' %}

{% block content %}
<div class="container-fluid">

    <div class="row">
        <header class="col-8">
            <div class="jumbotron">
                <h1 class="display-4">{{ scene.title }}</h1>
                <p class="lead">About text goes here.</p>
            </div>
        </header>
        <div class="col-4">
            <div class="row">
                <div class="col">
                    <h2>Characters</h2>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <a class="btn btn-primary" href="#">Add Character</a>
                </div>
            </div>
            <div class="my-3" style="overflow: scroll; max-height: 150px;">
                Allice <br />
                Allice <br />
                Allice <br />
                Allice <br />
                Allice <br />
                Allice <br />
            </div>
        </div>
    </div>
    <div class="row mb-3">
        <div class="col">
            <a class="btn btn-primary" href="#">Add Dialogue</a>
        </div>
    </div>
    <dl class="row">
        {% for d in scene.dialogues.all %}
        <dt class="col-sm-3">{{ d.character.name }}</dt>
        <dd class="col-sm-9">{{ d.content }}</dd>
        {% empty %}
        <dt class="col-sm-3">No one</dt>
        <dd class="col-sm-9">Nothing to say.<dd>
        {% endfor %}
    </dl>
</div>
{% endblock content %}

src/stories/templates/stories/scene_form.html
{% extends 'profile.html' %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col">
            <h1 class="py-3">Create Scene</h1>
            <form class="pb-3" method="post" novalidate>
                {% csrf_token %}
                <div class="form-group">
                    {{ form.title.errors }}
                    <label for="{{ form.title.id_for_label }}">Title:</label>
                    {{ form.title }}
                </div>
                <div class="form-group">
                    {{ form.position.errors }}
                    <label for="{{ form.position.id_for_label }}">Positon:</label>
                    {{ form.position }}
                </div>
                <button type="submit" class="btn btn-primary rounded-pill">Save</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

src/stories/templates/stories/scene_list.html
{% extends 'profile.html' %}

{% block content %}

<div class="container-fluid">
    <div class="row">
        <header class="col">
            <h1>{{ story.title }}'s Characters</h1>
        </header>
    </div>
    <div class="row mb-3">
        <div class="col">
            <a class="btn btn-primary" href="{% url 'stories:author-characters' story.id %}">Add Characters</a>
        </div>
    </div>
    <div class="card-columns">
        {% for scene in act.scenes.all %}
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">{{ character.name }}</h4>
            </div>
        </div>
        {% empty %}
        <div class="card my-3">
            <div class="card-body">
                <p class="card-text">
                    {{ story.title }} doesn't have any characters yet.
                </p>
            </div>
        </div>
            
        {% endfor %}
    </div>
</div>

{% endblock content %}

src/stories/templates/stories/story_characters.html
{% extends 'profile.html' %}

{% block content %}

<div class="container-fluid">
    <div class="row">
        <header class="col">
            <h1>{{ story.title }}'s Characters</h1>
        </header>
    </div>
    <div class="row mb-3">
        <div class="col">
            <a class="btn btn-primary" href="{% url 'stories:author-characters' story.id %}">Add Characters</a>
        </div>
    </div>
    <div class="card-columns">
        {% for character in story.characters.all %}
        <div class="card">
            {% for photo in character.album.photos.all %}
                {% if photo.default and photo.album.name == character.album.name  %}
                    <img src="{{ MEDIA_URL }}{{photo.file}}" class="card-img-top" 
                    style="object-fit: cover; object-position: 100% 0; height: 337px;" alt="...">
                {% endif %}
            {% endfor %}
            <div class="card-body">
                <h4 class="card-title">{{ character.name }}</h4>
            </div>
        </div>
        {% empty %}
        <div class="card my-3">
            <div class="card-body">
                <p class="card-text">
                    {{ story.title }} doesn't have any characters yet.
                </p>
            </div>
        </div>
            
        {% endfor %}
    </div>
</div>

{% endblock content %}

src/stories/templates/stories/story_details.html
{% extends 'profile.html' %}

{% block content %}

<div class="container-fluid">
    <div class="row">
        <div class="col-4">
             {% for photo in story.album.photos.all %}
                {% if photo.default and photo.album.name == story.album.name  %}
                    <img src="{{ MEDIA_URL }}{{photo.file}}" class="card-img-top" 
                    style="object-fit: cover; object-position: 100% 0; height: 337px;" alt="...">
                {% endif %}
            {% endfor %}
        </div>
        <div class="col-8">
            <div class="card">
                <div class="card-header">
                    {{ story.title }}
                </div>
                <div class="card-body">
                    <h4 class="card-title">{{ story.title }}</h4>
                    <p class="card-text">Characters: 
                        <ul class="list-inline">
                        {% for sc in characters %}
                            <li class="list-inline-item">{{ sc.character.name }}: {{ sc.role }}</li>
                        {% endfor %}
                        </ul>
                    </p>
                    <p class="card-text">Acts: 
                        <ul class="list-unstyled">
                        {% for act in story.acts.all %}
                            <li>{{ act.act_number }}: {{ act.title }}</li>
                        {% endfor %}
                        </ul>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

src/stories/templates/stories/story_form.html
{% extends 'profile.html' %}


{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col">
            <h1 class="py-3">Create Story</h1>
            <form class="pb-3" method="post" enctype="multipart/form-data" novalidate>
                {% csrf_token %}
                <div class="form-group">
                    {{ form.title.errors }}
                    <label for="{{ form.title.id_for_label }}">Title:</label>
                    {{ form.title }}
                </div>
                <div class="form-group">
                    {{ form.photo.errors }}
                    <label for="{{ form.photo.id_for_label }}">Photo:</label>
                    {{ form.photo }}
                </div>
                <button type="submit" class="btn btn-primary rounded-pill">Save</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}