src/files/urls.py
from django.urls import include, path

from . import views

urlpatterns = [
    path('files/', include(([
        path('', views.files_home_view, name="files_home"),
        path('download/', views.download_view, name="download_file"),
    ], 'files'), namespace='files')),
]

src/openlit/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('pages.urls')),
    path('', include('characters.urls')),
    path('', include('stories.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/private_messages/urls.py
from django.urls import include, path

from . import views

urlpatterns = [
    path('messages/', include(([
        path('<int:pk>/inbox/', views.inbox, name='inbox'),
        path('<int:pk>/outbox/', views.outbox, name='outbox'),
        path('compose/', views.compose, name='compose'),
    ], 'private_messages'), namespace='messages')),
]

src/private_messages/models.py
from django.conf import settings
from django.db import models

from accounts.models import UserProfile

# Create your models here.
class Message(models.Model):
    subject = models.CharField(max_length=255)
    body = models.TextField(null=True, blank=True)
    sender = models.ForeignKey(UserProfile, related_name='messages_sent', on_delete=models.CASCADE)
    recipients = models.ManyToManyField(UserProfile, related_name='messages_recieved')
    parent = models.ForeignKey('self', related_name='replies', on_delete=models.CASCADE, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    published = models.BooleanField(default=False)

    def __str__(self):
        return self.sender.user.email + ": " + self.subject
    

src/private_messages/forms.py
from django import forms
from django.db import transaction
from .models import Message
from accounts.models import UserProfile

class MessageForm(forms.ModelForm):
    subject = forms.CharField(max_length=255, widget=forms.TextInput(attrs={'class':'form-control'}))
    body = forms.CharField(widget=forms.Textarea(attrs={'class' : 'form-control', 'rows':'3'}))
    #recipients = forms.ModelMultipleChoiceField(widget=forms.SelectMultiple(attrs={'class':'form-control'}))
    # published = forms.BooleanField(required=False, widget=forms.CheckboxInput(attrs={'class': 'form-check-input'}))
    
    class Meta:
        model = Message
        fields = ['subject', 'body', 'recipients',]
        widgets = {
            'recipients' : forms.SelectMultiple(attrs={'class':'form-control'})
        }

    def __init__(self, user, *args, **kwargs):
        super(MessageForm, self).__init__(*args, **kwargs)
        profile = UserProfile.objects.get(user=user)
        self.fields['recipients'].queryset = profile.contacts.all()

src/private_messages/views.py
from django.shortcuts import render, redirect, get_object_or_404

from .models import Message
from .forms import MessageForm
from accounts.models import UserProfile

# Create your views here.
def inbox(request, pk, template_name='private_messages/inbox.html'):
    # get the current user
    user = UserProfile.objects.get(pk=pk)
    # get a list of messages that the current user is the receipent of
    messages = Message.objects.filter(recipients=user)
    data = {}
    data['messages'] = messages
    return render(request, template_name, data)

def outbox(request, pk, template_name='private_messages/outbox.html'):
    # get the current user
    user = UserProfile.objects.get(pk=pk)
    # get a list of messages that the current user is the receipent of
    messages = Message.objects.filter(sender=user)
    data = {}
    data['messages'] = messages
    return render(request, template_name, data)

def compose(request, template_name='private_messages/message_form.html'):
    form = MessageForm(request.user, request.POST or None)
    if form.is_valid():
        c = form.save(commit=False)
        c.sender = request.user.profile
        c.save()
        form.save_m2m()
        return redirect('messages:inbox', request.user.profile.id)
    return render(request, template_name, {'form': form})

def message_details(request):
    pass

src/private_messages/templates/private_messages/inbox.html
{% extends 'profile.html' %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
           <div class="col">
                <h1 class="py-3">Inbox</h1>
                <div class="my-2">
                    <a href="{% url 'messages:compose' %}" class="btn btn-custom rounded-pill"><i class="fas fa-pen-square"></i> Compose</a> 
                    <a href="{% url 'messages:outbox' request.user.profile.id %}" class="btn btn-custom rounded-pill"><i class="fas fa-share-square"></i> Outbox</a>
                </div>
                
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">Subject</th>
                            <th scope="col">Sender</th>
                            <th scope="col">Date</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for message in messages %}
                            <td>{{ message.subject }}</td> 
                            <td>{{ message.sender.user.name }}</td>
                            <td>{{ message.created_at }}</td>
                        {% endfor %}
                    </tbody>
                </table>
           </div> 
        </div>
    </div>
{% endblock content %}

src/private_messages/templates/private_messages/message_form.html
{% extends 'profile.html' %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col">
            <h1 class="py-3">Compose Message</h1>
            <form class="pb-3" method="post" novalidate>
                {% csrf_token %}
                <div class="form-group">
                    {{ form.subject.errors }}
                    <label for="{{ form.subject.id_for_label }}">Subject:</label>
                    {{ form.subject }}
                </div>
                <div class="form-group">
                    {{ form.body.errors }}
                    <label for="{{ form.body.id_for_label }}">Body:</label>
                    {{ form.body }}
                </div>
                <div class="form-group">
                    {{ form.recipients.errors }}
                    <label for="{{ form.recipients.id_for_label }}">Recipients:</label>
                    {{ form.recipients }}
                </div>
                <button type="submit" class="btn btn-custom rounded-pill">Save</button>
                <a href="{% url 'messages:inbox' request.user.profile.id %}" class="btn btn-secondary rounded-pill">Cancel</a>
            </form>
        </div>
    </div>
</div>
    
{% endblock content %}

src/private_messages/templates/private_messages/outbox.html
{% extends 'profile.html' %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col">
            <h1 class="py-3">Outbox</h1>
            <div class="py-2">
                <a href="{% url 'messages:compose' %}" class="btn btn-custom rounded-pill"><i class="fas fa-pen-square"></i> Compose</a> 
                <a href="{% url 'messages:inbox' request.user.profile.id %}" class="btn btn-custom rounded-pill"><i class="fas fa-inbox"></i> Inbox</a>
            </div>
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Subject</th>
                        <th scope="col">Recipients</th>
                        <th scope="col">Date</th>
                    </tr>
                </thead>
                <tbody>
                    {% for message in messages %}
                        <td>{{ message.subject }}</td> 
                        <td>{% for recipient in message.recipients.all %}{{recipient.user.name}}, {% endfor %}</td>
                        <td>{{ message.created_at }}</td>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock content %}